SELECT
    M.MEMBER_NAME,
    R.REVIEW_TEXT,
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE M
JOIN REST_REVIEW R
    ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM (
        SELECT
            MEMBER_ID,
            DENSE_RANK() OVER (ORDER BY COUNT(*) DESC) AS RNK
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    ) T
    WHERE RNK = 1
)
ORDER BY
    R.REVIEW_DATE ASC,
    R.REVIEW_TEXT ASC;

-- SELECT
--     M.MEMBER_NAME,
--     R.REVIEW_TEXT,
--     DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
-- FROM MEMBER_PROFILE M
-- JOIN REST_REVIEW R
--     ON M.MEMBER_ID = R.MEMBER_ID
-- WHERE M.MEMBER_ID = (
--     SELECT MEMBER_ID
--     FROM REST_REVIEW
--     GROUP BY MEMBER_ID
--     ORDER BY COUNT(*) DESC
--     LIMIT 1
-- )
-- ORDER BY
--     R.REVIEW_DATE ASC,
--     R.REVIEW_TEXT ASC;