-- 코드를 입력하세요
-- 서브쿼리에서 MAX값을 구했기 때문에, 그냥 원본 컬럼을 SELECT 해줘야함
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN (
    SELECT CATEGORY, MAX(PRICE) AS PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유') 
    GROUP BY CATEGORY
)
ORDER BY MAX_PRICE DESC

